databases:
  - name: bins
    user: kaushal
    plan: free
    region: oregon

services:
  - type: web
    name: bins
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bins
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  